In [4]:
import numpy as np

In [2]:
l1=[1,2,3,4,5]
x0=np.array(l1)

In [3]:
x0

array([1, 2, 3, 4, 5])

In [11]:
x1=np.array([[1,True],[1,'a']])

In [12]:
#Types gets converted to string
x1

array([['1', 'True'],
       ['1', 'a']],
      dtype='|S21')

In [16]:
#outer most to inner most
x3=np.ones((3,2,2,1))
x3

array([[[[ 1.],
         [ 1.]],

        [[ 1.],
         [ 1.]]],


       [[[ 1.],
         [ 1.]],

        [[ 1.],
         [ 1.]]],


       [[[ 1.],
         [ 1.]],

        [[ 1.],
         [ 1.]]]])

In [18]:
np.arange(3,10,2.3)

array([ 3. ,  5.3,  7.6,  9.9])

In [25]:
np.diag([1,2,4])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

In [24]:
np.diag([[1,2,4],[2,3,4]])

array([1, 3])

In [30]:
np.ones(4).shape

(4,)

In [32]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [34]:
np.ones((1,4)).shape

(1, 4)

In [35]:
np.ones((1,4))

array([[ 1.,  1.,  1.,  1.]])

difference between (4,1) and (4,)

In [37]:
[1,2,3]+[3,4,5]

[1, 2, 3, 3, 4, 5]

In [36]:
np.arange(5)+np.arange(5)

array([0, 2, 4, 6, 8])

In [45]:
np.transpose(np.arange(5)),np.arange(5).T

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [46]:
np.arange(5)*np.transpose(np.arange(5))

array([ 0,  1,  4,  9, 16])

In [47]:
np.dot((np.arange(5)),np.arange(5))

30

In [57]:
np.array([[1,2],[3,4],[5,6]]).flatten()

array([1, 2, 3, 4, 5, 6])

In [55]:
#First flatten and then does reshape
np.array([[1,2],[3,4],[5,6]]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.array([[1,2],[3,4],[5,6]]).T

array([[1, 3, 5],
       [2, 4, 6]])

#slicing

In [58]:
blist=[[1,2],[3,4]]
blist[1:][1:]

[]

In [59]:
(blist[1:])#only one element

[[3, 4]]

In [61]:
(blist[1:])[1:]#so we dont get any for 1:

[]

In [71]:
#for array
x1[1:,:]

array([['1', 'a']],
      dtype='|S21')

In [76]:
a=np.array([[1,2],[2,3],[3,4]])

In [78]:
a.sum(axis=1)

array([3, 5, 7])