In [1]:
import numpy as np
def softmax(x):
    if x.ndim<=1:
        x=x-np.max(x)
        ex=np.exp(x)
        return ex/ np.sum(ex)
    else:
        print("bigger dimension")
    
    return dist

In [4]:
#print(softmax(np.array([[1,2],[3,4]])))
print(softmax(np.array([1,2])))

[ 0.26894142  0.73105858]


In [75]:
X=np.array([[1,2],[3,4],[5,6]])

In [69]:
#ROW BASED
ps = np.empty(X.shape)
for i in range(X.shape[0]):
    ps[i,:]  = np.exp(X[i,:])
    ps[i,:] /= np.sum(ps[i,:])
ps

array([[ 0.26894142,  0.73105858],
       [ 0.26894142,  0.73105858],
       [ 0.26894142,  0.73105858]])

In [83]:
#ROW BASED - max substraction
X=np.array([[101,102],[-1,-2]])
ps = np.empty(X.shape)
for i in range(X.shape[0]):
    ps[i,:]  = np.exp(X[i,:]-np.max(X[i,:]))
    ps[i,:] /= np.sum(ps[i,:])
ps

array([[ 0.26894142,  0.73105858],
       [ 0.73105858,  0.26894142]])

In [71]:
#Column Based
ps = np.empty(X.shape)
for i in range(X.shape[1]):
    ps[:,i]  = np.exp(X[:,i])
    ps[:,i] /= np.sum(ps[:,i])
ps

array([[ 0.01587624,  0.01587624],
       [ 0.11731043,  0.11731043],
       [ 0.86681333,  0.86681333]])

In [72]:
#Column Based - max substraction
ps = np.empty(X.shape)
for i in range(X.shape[1]):
    ps[:,i]  = np.exp(X[:,i]-np.max(X[:,i]))
    ps[:,i] /= np.sum(ps[:,i])
ps

array([[ 0.01587624,  0.01587624],
       [ 0.11731043,  0.11731043],
       [ 0.86681333,  0.86681333]])

In [73]:
#More than 2 dimensions
#X=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
X = np.random.uniform(size = (3,3,2))

In [65]:
ps = np.empty(X.shape)
for i in range(X.shape[0]):
    ps[i,:]  = np.exp(X[i,:]-np.max(X[i,:]))
    ps[i,:] /= np.sum(ps[i,:])
ps

array([[[ 0.11603319,  0.18764596],
        [ 0.12960174,  0.16534581],
        [ 0.27042352,  0.13094978]],

       [[ 0.09667839,  0.21746135],
        [ 0.21415197,  0.20054871],
        [ 0.08911875,  0.18204084]],

       [[ 0.15852109,  0.16052897],
        [ 0.26699745,  0.15749931],
        [ 0.10729948,  0.14915369]]])

In [77]:
X=np.array([1,2])
y = np.atleast_2d(X)
y

array([[1, 2]])

In [81]:
#ROW BASED
X=np.array([[1,2],[3,4],[5,6]])
softmax = np.empty(X.shape)
for i in range(X.shape[0]):
    softmax  = np.exp(X-np.max(X,axis=0),0)
    softmax /= np.sum(ps[i,:])
softmax

TypeError: return arrays must be of ArrayType